name: Build Kahfi APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Flutter Project (if needed)
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Get Packages
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kahfi-APK
          path: build/app/outputs/flutter-apk/app-release.apk
